apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world
        image: magadankharich/hello_world
        ports:
        - containerPort: 32777
